// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNh31VPNMtYGVGMpV_YVTjUXattp-Yom0',
    appId: '1:399811753599:web:5135e37b24c079448af14a',
    messagingSenderId: '399811753599',
    projectId: 'itechon-57df1',
    authDomain: 'itechon-57df1.firebaseapp.com',
    storageBucket: 'itechon-57df1.appspot.com',
    measurementId: 'G-R7ZNDTG3ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0GEXojueZmGKRm3XXOcLbcM3tLFK1Ow',
    appId: '1:399811753599:android:ac02ad4adc29baf48af14a',
    messagingSenderId: '399811753599',
    projectId: 'itechon-57df1',
    storageBucket: 'itechon-57df1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrVgrsZ_6tj_8rYWhWE02V7UpQ0eZxwA',
    appId: '1:399811753599:ios:d540a267f61d26bf8af14a',
    messagingSenderId: '399811753599',
    projectId: 'itechon-57df1',
    storageBucket: 'itechon-57df1.appspot.com',
    iosClientId: '399811753599-mtedtj9d6b69ibv72f2uhuc1o3v9dfj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.itechon',
  );
}
